# Generated by Django 5.2.6 on 2025-12-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoice_products_invoice_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='user',
        ),
    ]
